language: node_js
node_js: 5.3.0
install: npm install
# Integration Build Steps
script:
  - npm run build
  - npm run eslint
notifications:
  email:
    - hossam.saraya@gmail.com
deploy:
  provider: heroku
  api_key: 1ba4bdd6-e8f1-4533-b976-47adca488686
  skip_cleanup: true
  app:
    master: meetup-react-app1
    staging: staging-meetup-react-app1
